---
stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ21N22"
    buildDescriptor: "helloworldui5/mta.yaml"
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.ap21.hana.ondemand.com"
      org: "f007d03btrial"
      space: "dev"
      credential: "deployonbtp"
