---
stages:
  build:
    steps:
      mtaBuild:
        source: "helloworldui5"
        buildToolVersion: "MBTJ21N22"
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.ap21.hana.ondemand.com"
      org: "f007d03btrial"
      space: "dev"
      credential: "deployonbtp"
