---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16"
stages:
  build:
    source: "helloworldui5"
    npmExecuteLint: false
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.ap21.hana.ondemand.com"
      org: "f007d03btrial"
      space: "dev"
      credential: "deployonbtp"
